# docker-compose.yml
version: "3"
services:
  postgres:
    container_name: node_temp_db_container
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8012:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
volumes:
  pg-dataset: